---
title: "About This Website"
---

- Visit [**Prepreocessing**](Vignettes/dp.html) tab to see the workflow up to today.

# MODELS

Here is a short description of the results under **Models** tab.

1. [**Models/Model 1**](Vignettes/PT_1.html): 

    - Cross-validation

    - 3527 speed observations
    
    - data as replicates

2. [**Models/Model 2**](Vignettes/PT_2.html): 

    - Cross-validation

    - all speed observations
    
    - data as replicates

3. [**Models/Model 3**](Vignettes/PT_3.html): 

    - Cross-validation

    - all and some speed observations
    
    - data as a whole

4. [**Models/Model 4**](Vignettes/PT_4.html): 

    - Cross-validation

    - all and some speed observations
    
    - data as replicates (this is the only difference with Model 3)
    
5. [**Models/Model 5**](Vignettes/PT_5.html): 

    - No cross-validation
    
    - data as replicates
    
    - `sf_graph$add_observations(data = data, group = "day", clear_obs = TRUE)`
    
6. [**Models/Model 6**](Vignettes/PT_6.html): 

    - No cross-validation
    
    - data as replicates
    
    - `sf_graph$add_observations(data = data, group = "day", normalized = TRUE, clear_obs = TRUE)` **This is the only difference with Model 5. Conclussion: Adding normalized = TRUE` does not make any difference. Explanation: See [**Tips/Tip 1**](Vignettes/Nuances/N1.html).**
    
    
7. [**Models/Model 7**](Vignettes/PT_7.html): 

    - INLA implementation
    
    - data as replicates
    
8. [**Models/Model 8**](Vignettes/PT_8.html): 

    - `start.theta = theta.prior.mean = c(fit.rspde$summary.log.std.dev$mode, fit.rspde$summary.log.range$mode, rep(0, (ncol(B.sigma)-3)))`
    
    - data as replicates
    
9. [**Models/Model 9**](Vignettes/PT_9.html): 

    - `sf_graph$edgeweight_to_data()` is used directly in this file.

    - `start.theta = theta.prior.mean = c(fit.rspde$summary.log.std.dev$mode, fit.rspde$summary.log.range$mode, rep(0, (ncol(B.sigma)-3)))`
    
    - data as replicates
    
10. [**Models/Model 10**](Vignettes/PT_10.html)

    - Comparison between default prior and priors changed to `start.theta = theta.prior.mean = c(fit.rspde$summary.log.std.dev$mode, fit.rspde$summary.log.range$mode, rep(0, (ncol(B.sigma)-3)))` and `theta.prior.prec = diag(rep(20,length(init.vec.theta)))`.
    
    - `"Models_output/distmatrixfixed.RData"` was created here.
    
    - Variable `GROUPS` was created and used here.

11. [**Models/Model 11**](Vignettes/PT_11.html)

    - We consider a covariate and estimate `nu`
    
    
12. [**Models/Model 12**](Vignettes/PT_12.html)

    - We consider only the field and estimate `nu`
    
    
13. [**Models/Model 13**](Vignettes/PT_13.html)

    - We consider a covariate, estimate `nu`, and reduce the mesh size from `h = 0.05` to `h = 0.01`.
    
    
14. [**Models/Model 14**](Vignettes/PT_14.html)

    - Just to compute `MSE_nearest_neighbor`.
  
15. [**Models/Model 15**](Vignettes/PT_15.html)

    - Same as Model 14 but now the nearest neighbor after removing observations within a radius.

    - Here we do `save(distance, mse.vector, file = here("Models_output/mse.vector.RData"))`.
    

16. [**Models/Model 16**](Vignettes/PT_16.html)

    - Just to check after reinstalling the packages.
    
    - `nu` estimated and `gaussian` family.
    
17. [**Models/Model 17**](Vignettes/PT_17.html)

    - same as Model 16 but with `T` family.
     
18. [**Models/Model 18**](Vignettes/PT_18.html)

    - same as Model 16 but with `nbinomial` family.
     
# HIGHWAYS
    
Here is a short description of the results under **Highways** tab.
    
0. [**Highways/Highways0**](Vignettes/Highways/Highways0.html)

    - this is to show the data and the graph
    
1. [**Highways/Highways1**](Vignettes/Highways/Highways1.html)

    - `nu` = 0.5
    

2. [**Highways/Highways2**](Vignettes/Highways/Highways2.html)

    - same as `Highways1`, except `nu.upper.bound` = 1.5
    

3. [**Highways/Highways3**](Vignettes/Highways/Highways3.html)

    - same as `Highways2`, except `h` = 0.01
    
    - **Conclusion. Changing the mesh size does not make any difference.**
    
4. [**Highways/Highways4**](Vignettes/Highways/Highways4.html)

    - `h` = 0.05
    
    - `nu.upper.bound` = 1.5
    
    - `family` = "T"
    
5. [**Highways/Highways5**](Vignettes/Highways/Highways5.html)

    - `h` = 0.05
    
    - `nu` = 0.5
    
    - `family` = "T"
    
6. [**Highways/Highways6**](Vignettes/Highways/Highways6.html)

    - `h` = 0.05
    
    - `nu` = 0.5
    
    - `family` = "nbinomial"
    
7. [**Highways/Highways7**](Vignettes/Highways/Highways7.html)

    - `h` = 0.05
    
    - `nu` = 0.5
    
    - `family` = "gaussian"
    
    - `mutate(across(c("speed", "SpeedLimit"), ~standardize(.)))`
    
    
8. [**Highways/Highways8**](Vignettes/Highways/Highways8.html)

    - Parameters as usual. That is, `h` = 0.05, `nu` = 0.5, `family` = "gaussian", `mutate(across(c(SpeedLimit"), ~standardize(.)))`.
    
    - Simulated data for stationary and nonstationary separately.
    
    - **Conclusion: Modeling are working fine. Crossvalidation not so much. Error in crossvalidation corrected in the following vignettes.**
    
    
9. [**Highways/Highways9**](Vignettes/Highways/Highways9.html)

    - Parameters as usual. That is, `h` = 0.05, `nu` = 0.5, `family` = "gaussian", `mutate(across(c(SpeedLimit"), ~standardize(.)))`.
    
    - Simulated data only for nonstationary model.
    
    - Initial parameters for the nonstationary from the stationary. That is, we set `start.theta = init.vec.theta` and `theta.prior.mean = init.vec.theta`.
    
    
10. [**Highways/Highways10**](Vignettes/Highways/Highways10.html)

    - Similar as `Highways9` except that initial parameters for the nonstationary **do not come** from the stationary.
    
    - **Conclusion: The estimates are better in this case than in `Highways9`.**
    
    
11. [**Highways/Highways11**](Vignettes/Highways/Highways11.html)

    - Similar as `Highways1` except that crossvalidation is corrected.


12. [**Highways/Highways12**](Vignettes/Highways/Highways12.html)

    - Similar as `Highways11` except that `mutate(across(c("speed", "SpeedLimit"), ~standardize(.)))`.
    
    - **Conclusion: Not a change.**
    
    
13. [**Highways/Highways13**](Vignettes/Highways/Highways13.html)

    - Similar as `Highways10` except that simulated data only for stationary model.
    
    - **Conclusion: From Highway10 and Highway13 we can see that fitting a nonstationary model for stationary data has no benefit. The stationary model is better when the data is nonstationary.**
    
14. [**Highways/Highways14**](Vignettes/Highways/Highways14.html)

    - Just to show some visualizations.
    
15. [**Highways/Highways15**](Vignettes/Highways/Highways15.html)

    - Using bru_rerun() on Highways11
    

16. [**Highways/Highways16**](Vignettes/Highways/Highways16.html)

    - Fitting this model on highways11: speed ~ -1 + Intercept(1) + field()
    
17. [**Highways/Highways17**](Vignettes/Highways/Highways17.html)

    - Abort because distance matrix has one less row and column than the number of observations.
    
    - Here `day7142128_hour8` is used.
    
    - Also tried `day7142128_hour9` but gave some error when using `19Remove_zero_speed_for_long_periods.R` script.
    
18. [**Highways/Highways18**](Vignettes/Highways/Highways18.html)

    - This one run fine. **No improvement in the results.**
    
    - Here `day7142128_hour16` is used.
    
19. [**Highways/Highways19**](Vignettes/Highways/Highways19.html)

    - Abort because of this error: `Error in `[<-`(`*tmp*`, graph.temp$.__enclos_env__$private$data[["__dummy"]],  : subscript out of bounds`
    
    - Here `day8152229_hour9` is used.
    
    
20. [**Highways/Highways20**](Vignettes/Highways/Highways20.html)

    - Abort because the distmatrix dimension do not math with the data.
    
    - Here `day6132027_hour8` is used.
    
    
21. [**Highways/Highways21**](Vignettes/Highways/Highways21.html)
    
    - Here `day6132027_hour16` is used.
    
    - Abort because the distmatrix dimension do not math with the data.
    
    